---
collections:
  - name: ansible.posix
  - name: community.docker
roles:
  - src: geerlingguy.apache
  - src: eugene_krivosheyev.artifactory
  - src: geerlingguy.gitlab
  - src: geerlingguy.docker
  - src: geerlingguy.pip