---
- name: Create GitLab runner Docker container
  docker_container:
    name: gitlab-runner
    image: gitlab/gitlab-runner:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/gitlab-runner/config:/etc/gitlab-runner
    state: started
    env:
      TZ: "America/Denver"