---
- name: Create GitLab runner Docker container
  docker_container:
    name: "{{ item }}"
    image: gitlab/gitlab-runner:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "/srv/{{ item }}/config:/etc/gitlab-runner"
    state: started
    container_default_behavior: no_defaults
    env:
      TZ: "America/Denver"
  with_sequence: start=1 end=4 format=gitlab-runner-%02x
  register: runners_created
  notify: register runners